%% GrosmarkAD
files_to_redo = {'A:\Data\GrosmarkAD\Cicero\Cicero_09012014',...
    'A:\Data\GrosmarkAD\Cicero\Cicero_09102014',...
    'A:\Data\GrosmarkAD\Cicero\Cicero_09172014',...
    'A:\Data\GrosmarkAD\Buddy\Buddy_06272013',...
    'A:\Data\GrosmarkAD\Achilles\Achilles_10252013',...
    'A:\Data\GrosmarkAD\Achilles\Achilles_11012013',...
    'A:\Data\GrosmarkAD\Gatsby\Gatsby_08022013',...
    'A:\Data\GrosmarkAD\Gatsby\Gatsby_08282013'};

basepath = 'D:\projects\test\Cicero_09012014';
% CAREFULL, will overwrite spikes.cellinfo
spikes = loadSpikes(...
                    'basepath',basepath,...
                    'saveMat',true,...
                    'format','Klustakwik',...
                    'getWaveformsFromDat',false,...
                    'getWaveformsFromSource',true...
                    );

% highlighted all metrics in "include_metrics"
cell_metrics = ProcessCellMetrics('basepath',basepath,...
    'showGUI',false,...
    'spikes',spikes);

% GUI to manually curate cell classification
cell_metrics = CellExplorer('metrics',cell_metrics);

% make swr metrics
basename = bz_BasenameFromBasepath(basepath);

load(fullfile(basepath,[basename,'.ripplesALL.event.mat']))

[ripSpk] = bz_getRipSpikes('basepath',basepath,...
    'events',ripples.times,...
    'saveMat',false);
SWRunitMetrics = bz_unitSWRmetrics(ripSpk);

save(fullfile(basepath,[basename '.SWRunitMetrics.mat']),'unitRip')





