---
title: "multi_region_assembly"
author: "ryan"
date: "7/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)
library(effectsize)
library(EMAtools)
```

```{r}

data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/assembly_multi_region_react_df.csv")

data$basepath = factor(data$basepath)
data$epoch = factor(data$epoch)
data$single_cross_region_label = factor(data$single_cross_region_label)
data$animal_id = factor(data$animal_id)
data$assembly_n = factor(data$assembly_n)


summary(data)
```

```{r}

temp_data <- data[data$single_cross_region_label == "deep_mec" | data$single_cross_region_label == "superficial_mec",]
temp_data$single_cross_region_label = factor(temp_data$single_cross_region_label)

mdl_boxcox <- boxcox(strength ~ single_cross_region_label, data=temp_data, lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

# temp_data$y_trans <- temp_data$strength^max_lambda
temp_data$y_trans <- log(temp_data$strength)

m1 = lmer(y_trans ~ single_cross_region_label + (1 | animal_id/basepath), data = temp_data, REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")
plot(y_trans ~ single_cross_region_label, data=temp_data)
```

```{r}
temp_data <- data[data$single_cross_region_label == "deep_pfc" | data$single_cross_region_label == "superficial_pfc",]
temp_data$single_cross_region_label = factor(temp_data$single_cross_region_label)

mdl_boxcox <- boxcox(strength ~ single_cross_region_label, data=temp_data, lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

temp_data$y_trans <- temp_data$strength^max_lambda

m1 = lmer(y_trans ~ single_cross_region_label + (1 | animal_id/basepath), data = temp_data, REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")
plot(y_trans ~ single_cross_region_label, data=temp_data)

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```