---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)
library(effectsize)
library(EMAtools)
```

```{r}
data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/pairwise_corr_readout.csv")

data <- data[data$sublayer == "Deep" | data$sublayer == "Superficial" ,]

data <- data[!is.nan(data$corrcoef_pre_post),]
data <- data[!is.nan(data$corrcoef_pre_post_abs),]

# data <- data[data$consider_remove=="False",]

data$corrcoef.1 <- as.numeric(data$corrcoef.1)
data$corrcoef.2 <- as.numeric(data$corrcoef.2)
data$corrcoef <- as.numeric(data$corrcoef)

data$cor_post <- abs(data$corrcoef)
data$cor_pre <- abs(data$corrcoef.1)
data$cor_task <- abs(data$corrcoef.2)

data$basepath = factor(data$basepath)
data$animal_id = factor(data$animal_id)
data$region = factor(data$region)
data$sublayer = factor(data$sublayer)
data$region_sublayer = factor(data$region_sublayer)
data$ref_uid = factor(data$ref_uid)
data$target_uid = factor(data$target_uid)
data$unique_uid_pair = factor(data$unique_uid_pair)
data$unique_uid_basepath = factor(data$unique_uid_basepath)


# data$UID  = factor(data$UID)

summary(data)
```

```{r}

mdl_boxcox <- boxcox(corrcoef_pre_post_abs ~ sublayer + region, data=data, lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

# data$y_trans <- log(data$corrcoef_pre_post_abs)
data$y_trans <- data$corrcoef_pre_post_abs^max_lambda

m1 = lmer(y_trans ~ sublayer * region + (1 | animal_id/basepath/unique_uid_basepath), data = data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(y_trans ~ sublayer * region, data = data)
```
```{r}
hist(data$r2_pre_post,100)
```

```{r}

data$r2_pre_post_offset <- data$r2_pre_post+1

mdl_boxcox <- boxcox(r2_pre_post_offset ~ sublayer, data=data[data$region=="MEC",], lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

data$y_trans <- data$r2_pre_post_offset^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath/unique_uid_basepath), data = data[data$region=="MEC",],REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(y_trans ~ sublayer , data = data[data$region=="MEC",])
```

```{r}

mdl_boxcox <- boxcox(r2_pre_post_offset ~ sublayer, data=data[data$region=="PFC",], lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

data$y_trans <- data$r2_pre_post_offset^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath/unique_uid_basepath), data = data[data$region=="PFC",],REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(y_trans ~ sublayer , data = data[data$region=="PFC",])
```


```{r}

mdl_boxcox <- boxcox(corrcoef_pre_post_abs ~ sublayer, data=data[data$region=="MEC",], lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

# data$y_trans <- log(data$corrcoef_pre_post_abs)
data$y_trans <- data$corrcoef_pre_post_abs^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath/unique_uid_basepath), data = data[data$region=="MEC",],REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(y_trans ~ sublayer , data = data[data$region=="MEC",])
```


```{r}

mdl_boxcox <- boxcox(corrcoef_pre_post_abs ~ sublayer, data=data[data$region=="PFC",], lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

# data$y_trans <- log(data$corrcoef_pre_post_abs)
data$y_trans <- data$corrcoef_pre_post_abs^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath/unique_uid_basepath), data = data[data$region=="PFC",],REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(y_trans ~ sublayer , data = data[data$region=="PFC",])
```


```{r}
data$r2_pre <- data$cor_pre^2

mdl_boxcox <- boxcox(r2_pre ~ sublayer, data=data[data$region=="MEC",], lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

# data$y_trans <- log(abs(data$corrcoef.1))
data$y_trans <- data$r2_pre^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath/unique_uid_basepath), data = data[data$region=="MEC",],REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(y_trans ~ sublayer , data = data[data$region=="MEC",])
```


```{r}
data$r2_pre <- data$cor_pre^2

mdl_boxcox <- boxcox(r2_pre ~ sublayer, data=data[data$region=="PFC",], lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

# data$y_trans <- log(abs(data$corrcoef.1))
data$y_trans <- data$r2_pre^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath/unique_uid_basepath), data = data[data$region=="PFC",],REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(y_trans ~ sublayer , data = data[data$region=="PFC",])
```


```{r}

temp_data <- data[data$region=="MEC",]

# temp_data <- temp_data[!is.nan(temp_data$cor_pre),]
# temp_data <- temp_data[!is.na(temp_data$cor_pre),]

temp_data$cor_pre_abs <- abs(temp_data$cor_pre)+1

mdl_boxcox <- boxcox(cor_pre_abs ~ sublayer, data=temp_data, lambda = seq(-100, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

temp_data$y_trans <- temp_data$cor_pre_abs^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")
plot(y_trans ~ sublayer, data = temp_data)
```


```{r}

temp_data <- data[data$region=="PFC",]

# temp_data <- temp_data[!is.nan(temp_data$cor_pre),]
# temp_data <- temp_data[!is.na(temp_data$cor_pre),]

temp_data$cor_pre_abs <- abs(temp_data$cor_pre)+1

mdl_boxcox <- boxcox(cor_pre_abs ~ sublayer, data=temp_data, lambda = seq(-100, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

temp_data$y_trans <- temp_data$cor_pre_abs^max_lambda

m1 = lmer(y_trans ~ sublayer + (1 | animal_id/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")
plot(y_trans ~ sublayer, data = temp_data)
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```
