---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)
library(effectsize)
library(EMAtools)

```

```{r}

data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/temp_replay_participation_df.csv")
data <- data[data$deepSuperficial != "middle",]

data$basepath = factor(data$basepath)
data$animal_id = factor(data$animal_id)
data$deepSuperficial = factor(data$deepSuperficial)
data$epoch  = factor(data$epoch)
data$epoch_i  = factor(data$epoch_i)
data$epoch_rel_i  = factor(data$epoch_rel_i)
data$UID  = factor(data$UID)

# data$replay_type  = factor(data$replay_type)
# data$replay_layer  = factor(data$replay_layer)

summary(data)
```
```{r}
temp_data <- data[data$epoch_rel_i == 0 & data$n_replays > 2 & data$epoch == "linear",]
summary(temp_data)
```



```{r}
temp_data <- data[data$epoch_rel_i == 0 & data$n_replays > 40 & data$epoch == "linear",]

m1 = glmer(replay_par ~ deepSuperficial + (1|animal_id/basepath), weights=n_replays, data=temp_data,family="binomial")

summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

# a1 = anova(m1)
# F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")

plot(replay_par ~ deepSuperficial, data = temp_data)

```
```{r}
temp_data <- data[data$epoch_rel_i == 0 & data$n_replays > 2 & data$epoch == "linear",]

res <- t.test(replay_par ~ deepSuperficial, data = temp_data)
res
# 
# # temp_data$y_trans <- log(temp_data$replay_par+2)
# m1 = lm(replay_par ~ deepSuperficial, data = temp_data)
# summary(m1)
# plot(m1)

```

```{r}
temp_data <- data[data$epoch_rel_i == 0 & data$n_replays > 2 & data$epoch == "linear",]

temp_data$y_trans <- log(temp_data$replay_par+1)
m1 = lmer(y_trans ~ deepSuperficial + (1 | animal_id/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")

plot(y_trans ~ deepSuperficial, data = temp_data)

```


```{r}
# temp_data <- data[data$animal_id != "Rat10" & data$animal_id != "Rat11" & data$animal_id != "Rat08",]
# 
# 
# m1 = lmer(replay_par_rel_baseline ~ deepSuperficial + (1 | basepath), data = temp_data,REML=FALSE)
# summary(m1)
# 
# simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
# plot(simulationOutput)
# 
# a1 = anova(m1)
# F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)
# 
# lme.dscore(m1,data=temp_data,type="lme4")

```

```{r}
temp_data <- data[data$animal_id != "Rat10" & data$animal_id != "Rat11" & data$animal_id != "Rat08",]


m1 = lmer(replay_fr_rel_baseline ~ deepSuperficial + (1 | basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")


```

```{r}
temp_data <- data[data$n_replays > 2 & data$epoch_rel_i == 0 & data$epoch == "linear",]

hist(temp_data$normed_replay_fr)

plot(normed_replay_fr ~ deepSuperficial, temp_data)
```


```{r}
# temp_data <- data[data$n_replays > 2 & data$epoch_rel_i == 0 & data$epoch == "linear" & data$animal_id != "Rat10" & data$animal_id != "Rat11" & data$animal_id != "Rat08" & data$normed_replay_fr > -1,]

temp_data <- data[data$n_replays > 2 & data$epoch_rel_i == 0 & data$epoch == "linear",]

m1 = lmer(normed_replay_fr ~ deepSuperficial + (1 | basepath), data = temp_data, REML=FALSE)
summary(m1)


simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")

```