---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)
library(effectsize)
library(EMAtools)
library(sjmisc)
library(sjlabelled)

```

```{r}
citation("DHARMa")
```


```{r}
# data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/replay_participation_for_v7_task_post.csv")
data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/replay_participation_for_all_sessions_task_post.csv")
                  
data <- data[data$deepSuperficial == "Deep" | data$deepSuperficial == "Superficial",]
# data <- data[data$n_replays > 10,]
# data <- data[!is.nan(data$replay_df_gain_avg_to_replay),]
data <- data[!is.na(data$replay_par),]

data <- data[data$epoch == "linear_sleep",]

# data <- data[data$animal_id != "HMC2",]
# 
# data <- data[data$basepath == r"(Z:\\Data\\AYAold\\AB3\\AB3_38_41)" | 
#           data$basepath == r"(Z:\\Data\\AYAold\\AYA6\\day17)" | 
#           data$basepath == r"(Z:\\Data\\AYAold\\AYA6\\day19)" |
#           data$basepath == r"(Z:\\Data\\Can\\OML22\\day19)" |
#           data$basepath == r"(Z:\\Data\\Can\\OML22\\day8)" |
#           data$basepath == r"(Z:\\Data\\GirardeauG\\Rat10\\Rat10-20140702)" |
#           data$basepath == r"(Z:\\Data\\GirardeauG\\Rat11\\Rat11-20150310)" |
#           data$basepath == r"(Z:\\Data\\GirardeauG\\Rat11\\Rat11-20150313)" |
#           data$basepath == r"(Z:\\Data\\GirardeauG\\Rat11\\Rat11-20150314)" |
#           data$basepath == r"(Z:\\Data\\GirardeauG\\Rat11\\Rat11-20150315)" |
#           data$basepath == r"(Z:\\Data\\GrosmarkAD\\Cicero\\Cicero_09102014)" |
#           data$basepath == r"(Z:\\Data\\HMC1\\day10)" |
#           data$basepath == r"(Z:\\Data\\HMC1\\day14)" |
#           data$basepath == r"(Z:\\Data\\HMC1\\day9)" |
#           data$basepath == r"(Z:\\Data\\Kenji\\ec013.393_418)" |
#           data$basepath == r"(Z:\\Data\\Kenji\\ec013.677_699)" |
#           data$basepath == r"(Z:\\Data\\Kenji\\ec013.634_653)" |
#           data$basepath == r"(Z:\\Data\\Kenji\\ec013.656_674)"
#          ,]


data$basepath = factor(data$basepath)
data$animal_id = factor(data$animal_id)
data$deepSuperficial = factor(data$deepSuperficial)
data$epoch  = factor(data$epoch)
data$epoch_i  = factor(data$epoch_i)
data$UID  = factor(data$UID)

summary(data)
```

```{r}
unique(data$animal_id)
```

```{r}
m1 = glmer(replay_par ~ deepSuperficial + (1|basepath), weights=n_replays, data=data,family="binomial")


summary(m1)

testDispersion(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)
# 
# lme.dscore(m1,data=temp_data,type="lme4")
plot(replay_par ~ deepSuperficial, data = data)

# a1 = anova(m1)
# F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")


plot_model(m1,type = "re", value.size = .1)
plot_model(m1,type = "diag", value.size = .1)

# “est”, “re”, “eff”, “emm”, “pred”, “int”, “std”, “std2”, “slope”, “resid”, “diag”
```


```{r}
random_effects = ranef(m1)
random_effects$animal_id

# fixef(m1)
```

```{r}
# random_effects$animal_id[order(random_effects[["animal_id"]][["(Intercept)"]]),]

random_effects$animal_id %>% arrange(random_effects[["animal_id"]][["(Intercept)"]])
```

```{r}
data$y_trans <- data$replay_fr+2

mdl_boxcox <- boxcox(y_trans ~ deepSuperficial, data=data, lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

data$y_trans <- data$y_trans^max_lambda
  
# data$y_trans <- log(data$y_trans)

m1 = lmer(y_trans ~ deepSuperficial + (1 | animal_id/basepath), data = data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(replay_fr ~ deepSuperficial , data = data)

plot_model(m1,type = "re", value.size = .1)

```

```{r}
m1 = glmer(forward_replay_par ~ deepSuperficial + (1|animal_id/basepath), weights=n_forward_replays, data=data,family="binomial")


summary(m1)

testDispersion(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)
# 
# lme.dscore(m1,data=temp_data,type="lme4")
plot(forward_replay_par ~ deepSuperficial, data = data)

# a1 = anova(m1)
# F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
```

```{r}
m1 = glmer(reverse_replay_par ~ deepSuperficial + (1|animal_id/basepath), weights=n_reverse_replays, data=data,family="binomial")


summary(m1)

testDispersion(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)
# 
# lme.dscore(m1,data=temp_data,type="lme4")
plot(reverse_replay_par ~ deepSuperficial, data = data)

# a1 = anova(m1)
# F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
```

```{r}

data$forward_reverse_ratio <- (data$forward_replay_par / data$reverse_replay_par)

temp_data <- data[!is.infinite(data$forward_reverse_ratio),]
temp_data <- temp_data[!is.nan(temp_data$forward_reverse_ratio),]

temp_data$forward_reverse_ratio <- log(temp_data$forward_reverse_ratio+2)

m1 = lmer(forward_reverse_ratio ~ deepSuperficial + (1 | basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")
plot(forward_reverse_ratio ~ deepSuperficial , data = temp_data)

```



```{r}
data$y_trans <- data$replay_par

mdl_boxcox <- boxcox(y_trans ~ deepSuperficial, data=data, lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

data$y_trans <- data$y_trans^max_lambda
  
m1 = lmer(y_trans ~ deepSuperficial + (1 | animal_id/basepath), data = data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
```

```{r}
data$forward_reverse_ratio <- (data$forward_replay_par / data$reverse_replay_par)

temp_data <- data[!is.infinite(data$forward_reverse_ratio),]
temp_data <- temp_data[!is.nan(temp_data$forward_reverse_ratio),]
temp_data$forward_reverse_ratio
log(temp_data$forward_reverse_ratio+1)
```

## replay gain

```{r}

data[data$animal_id == "Rat08" | data$animal_id == "Gatsby" ,]
```

```{r}
temp_data <- data[data$animal_id != "Rat08" & data$animal_id != "Gatsby" ,]

temp_data <- temp_data[!is.nan(temp_data$replay_df_gain_avg_to_replay),]

temp_data$y_trans <- temp_data$replay_df_gain_avg_to_replay+1

mdl_boxcox <- boxcox(y_trans ~ deepSuperficial,data=temp_data, lambda = seq(-5, 10, length = 100))
max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]
max_lambda

summary(temp_data)
```

```{r}
# remove these rats
temp_data <- data[data$animal_id != "Rat08" & data$animal_id != "Gatsby" & data$animal_id != "OML22",]

# set var to y trans
temp_data$y_trans <- log(temp_data$replay_df_gain_avg_to_replay+1)

# use boxcox to find transform
# mdl_boxcox <- boxcox(y_trans ~ deepSuperficial,data=temp_data, lambda = seq(-5, 10, length = 100))
# max_lambda <- mdl_boxcox$x[max(mdl_boxcox$y) == mdl_boxcox$y]

# transform var
# temp_data$y_trans <- (temp_data$replay_df_gain_avg_to_replay+1)^max_lambda

# fit linear model
m1 = lmer(y_trans ~ deepSuperficial + (1|animal_id/basepath), data = temp_data,REML=FALSE)
summary(m1)

# check residuals
simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

# get eta squared
a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

# plot relationship
plot(y_trans ~ deepSuperficial , data = temp_data)

# get cohen's D
lme.dscore(m1,data=temp_data,type="lme4")
```



```{r}
data$y_trans <- log(data$replay_df_gain_avg_to_replay+2)

m1 = lm(y_trans ~ deepSuperficial, data = data)
summary(m1)

plot(m1)
```

```{r}
data$y_trans <- log(data$replay_fr)

m1 = lm(y_trans ~ deepSuperficial, data = data)
summary(m1)

plot(m1)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```