---
title: "replay_gain"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)
library(effectsize)
library(EMAtools)
```

```{r}
data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/replay_participation_for_all_sessions_task_post_replay_gain.csv")

data <- data[data$deepSuperficial == "Deep" | data$deepSuperficial == "Superficial" ,]

data <- data[!is.nan(data$replay_gain),]

data$basepath = factor(data$basepath)
data$animal_id = factor(data$animal_id)
data$deepSuperficial = factor(data$deepSuperficial)
data$UID  = factor(data$UID)

summary(data)
```

```{r}

data$trans_y <- log(data$replay_gain)

m1 = lmer(trans_y ~ deepSuperficial + (1 | basepath), data = data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=data,type="lme4")
plot(trans_y ~ deepSuperficial , data = data)
```

```{r}
m1 = lm(trans_y ~ deepSuperficial, data = data)
summary(m1)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
