---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)
library(effectsize)
library(EMAtools)

```

```{r}

data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/replay_participation_df.csv")

data$basepath = factor(data$basepath)
data$animal = factor(data$animal)
data$deepSuperficial = factor(data$deepSuperficial)
data$epoch  = factor(data$epoch)
data$replay_type  = factor(data$replay_type)
data$replay_layer  = factor(data$replay_layer)

summary(data)
```

```{r}

m1 = glmer(participation ~ deepSuperficial + (1|basepath), weights=n_replays, data=data,family="binomial")

summary(m1)

testDispersion(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)
# 
# lme.dscore(m1,data=temp_data,type="lme4")
plot(participation ~ deepSuperficial, data = data)

```

```{r}

m1 = glmer(participation ~ deepSuperficial + (1|basepath), weights=n_replays, data=data[data$epoch == "pre",],family="binomial")

summary(m1)

testDispersion(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)
# 
# lme.dscore(m1,data=temp_data,type="lme4")
plot(participation ~ deepSuperficial, data = data[data$epoch == "pre",])

```


```{r}

m1 = glmer(participation ~ deepSuperficial + (1|basepath/replay_type), weights=n_replays, data=data[data$epoch == "task",],family="binomial")

summary(m1)

testDispersion(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)
plot(participation ~ deepSuperficial, data = data[data$epoch == "task",])

```

```{r}

m1 = glmer(participation ~ deepSuperficial + (1|basepath/replay_type), weights=n_replays, data=data[data$epoch == "post",],family="binomial")

summary(m1)

testDispersion(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

plot(participation ~ deepSuperficial, data = data[data$epoch == "post",])

```





# Same with lmer



```{r}
temp_data <- data[data$epoch == "pre",]

temp_data$y_trans <- log(temp_data$participation+1)
  
m1 = lmer(y_trans ~ deepSuperficial + (1 | animal/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")

```

```{r}
data$y_trans <- log(data$participation+1)

temp_data <- data[data$epoch == "task",]

m1 = lmer(y_trans ~ deepSuperficial + (1 | basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")

```

```{r}
data$y_trans <- log(data$participation+1)

temp_data <- data[data$epoch == "post",]

m1 = lmer(y_trans ~ deepSuperficial + (1 | basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

lme.dscore(m1,data=temp_data,type="lme4")

```