---
title: "stats_deep_sup_state"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

data <- read.csv("Z:/home/ryanh/projects/ripple_heterogeneity/df_states.csv")

data <- data[data$ca1_layer != "Middle",]

data$basepath = factor(data$basepath)
data$basename = factor(data$basename)
data$animal = factor(data$animal)
data$putativeCellType = factor(data$putativeCellType)
data$brainRegion = factor(data$brainRegion)
data$deepSuperficial = factor(data$deepSuperficial)
data$rem_shift = factor(data$rem_shift)
data$non_rem_shift  = factor(data$non_rem_shift)
data$layer_rem_shift  = factor(data$layer_rem_shift)
data$state  = factor(data$state)
data$ca1_layer  = factor(data$ca1_layer)

summary(data)
```

```{r}

library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)
library(effectsize)

```

```{r}
temp_data <- data[data$state == "_WAKEepisode",]
temp_data$ripple_FRall_trans = log(temp_data$ripple_FRall+.1)


m1 = lmer(ripple_FRall_trans ~ ca1_layer + (1 | animal/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

```


```{r}
temp_data <- data[data$state == "_NREMepisode",]
temp_data$ripple_FRall_trans = log(temp_data$ripple_FRall+.1)


m1 = lmer(ripple_FRall_trans ~ ca1_layer + (1 | animal/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)
```

# ripple_particip _WAKEepisode

```{r}
temp_data <- data[data$state == "_WAKEepisode",]
temp_data$y_trans = log(temp_data$ripple_particip+.1)


m1 = lmer(y_trans ~ ca1_layer + (1 | animal/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

```

# ripple_particip _NREMepisode

```{r}
temp_data <- data[data$state == "_NREMepisode",]
temp_data$y_trans = log(temp_data$ripple_particip+.1)


m1 = lmer(y_trans ~ ca1_layer + (1 | animal/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

```

# ripple_GainParticip _WAKEepisode

```{r}
temp_data <- data[data$state == "_WAKEepisode",]
temp_data$y_trans = log(temp_data$ripple_GainParticip)


m1 = lmer(y_trans ~ ca1_layer + (1 | animal/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

```

# ripple_GainParticip _NREMepisode

```{r}
temp_data <- data[data$state == "_NREMepisode",]
temp_data$y_trans = log(temp_data$ripple_GainParticip)


m1 = lmer(y_trans ~ ca1_layer + (1 | animal/basepath), data = temp_data,REML=FALSE)
summary(m1)

simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
plot(simulationOutput)

a1 = anova(m1)
F_to_eta2(a1$`F value`, a1$NumDF, a1$DenDF)

```
