---
title: "deep_sup_remshift_state"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r}

data <- read.csv('Z:/home/ryanh/projects/ripple_heterogeneity/deep_sup_remshift_state.csv')

data$basepath = factor(data$basepath)
data$basename = factor(data$basename)
data$animal = factor(data$animal)
data$putativeCellType = factor(data$putativeCellType)
data$brainRegion = factor(data$brainRegion)
data$deepSuperficial = factor(data$deepSuperficial)
data$rem_shift = factor(data$rem_shift)
data$non_rem_shift  = factor(data$non_rem_shift)
data$layer_rem_shift  = factor(data$layer_rem_shift)
data$state  = factor(data$state)
data$state_layer  = factor(data$state_layer)

summary(data)
```

```{r}

library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)

```

```{r}
hist(log(data$ripple_FRall),100)
```

```{r}
data$ripple_FRall_trans = log(data$ripple_FRall)
m1 = lmer(ripple_FRall_trans ~ layer_rem_shift + (1 | animal/basepath), data = data,REML=FALSE)
summary(m1)

```

```{r}
plot(ripple_FRall_trans ~ layer_rem_shift, data = data)

plot(m1)

qqnorm(resid(m1))
qqline(resid(m1))
```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```