---
title: "stats_pairwise_corr_assembly"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
data <- read.csv('Z:/home/ryanh/projects/ripple_heterogeneity/assembly_unit_corrs/results/df.csv')

data$basepath = factor(data$basepath)
data$name = factor(data$name)
data$label = factor(data$label)
data$membership = factor(data$membership)
data$assembly_id <- factor(as.character(data$assembly_id))

summary(data)

```

```{r}

# data$assembly_id
```

## make var for simple effect
```{r}

data$simple_effect = "unknown"
data$simple_effect[data$label == "member_deep" | data$label == "member_sup"] = "member_single_layer"
data$simple_effect[data$label == "member_deep_sup"] = "member_cross_layer"
data$simple_effect = factor(data$simple_effect)

summary(data)
```


```{r}

length(unique(data$rho))
length(data$rho)

```

```{r}

library(tidyverse)
library(lme4)
library(lmerTest)
library(MASS)
library(DHARMa)
library(ggplot2)

```

```{r}
library(ggplot2)

p<-ggplot(data, aes(x=name, y=rho, color=membership)) +
  geom_boxplot()
p

```

```{r}
hist(data$rho,100)
hist(sqrt(data$rho + 1),100)
```

```{r}
data$rho_trans <- log(data$rho+1)
data$rho_trans <- data$rho


m1 = lmer(rho_trans ~ membership + (1 | name/basepath), data = data,REML=FALSE)
summary(m1)

```


```{r}
plot(m1)

qqnorm(resid(m1))
qqline(resid(m1))
```


```{r}
simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)
```


```{r}
plot(simulationOutput)
```

```{r}
plot(rho_trans ~ membership, data = data)
```


```{r}


```


```{r}

data_2 = data[!data$simple_effect == "unknown",]

data_2$rho_trans = log(data_2$rho+1)

m1 = lmer(rho_trans ~ simple_effect + (1 | name/basepath/assembly_id), data = data_2,REML=FALSE)
summary(m1)

```


```{r}
plot(m1)

qqnorm(resid(m1))
qqline(resid(m1))
```

```{r}
plot(rho_trans ~ simple_effect, data = data_2)

```

```{r}

# testDispersion(m1)
simulationOutput <- simulateResiduals(fittedModel = m1, plot = F)


```



```{r}
plot(simulationOutput)

```

```{r}
unique(data_2$name)
unique(data_2$basepath)

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

